//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCam_Mi_A1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCam_Mi_A1.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow USB Debugging.
        /// </summary>
        internal static string ADB_1 {
            get {
                return ResourceManager.GetString("ADB_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect the phone.
        /// </summary>
        internal static string ADB_2 {
            get {
                return ResourceManager.GetString("ADB_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable HAL3, EIS.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string Drivers_inf {
            get {
                return ResourceManager.GetString("Drivers_inf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try the 1.3 if 1.4.3 doesn&apos;t work.
        /// </summary>
        internal static string Drivers_inf2 {
            get {
                return ResourceManager.GetString("Drivers_inf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalized.
        /// </summary>
        internal static string finalizado {
            get {
                return ResourceManager.GetString("finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installing Google Camera....
        /// </summary>
        internal static string GCam_install {
            get {
                return ResourceManager.GetString("GCam_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you want to help:.
        /// </summary>
        internal static string Main_dona {
            get {
                return ResourceManager.GetString("Main_dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Install Drivers.
        /// </summary>
        internal static string Main_drivers {
            get {
                return ResourceManager.GetString("Main_drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable HAL3, EIS and install GCam.
        /// </summary>
        internal static string Main_GCam {
            get {
                return ResourceManager.GetString("Main_GCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locking bootloader....
        /// </summary>
        internal static string Main_pro_bootblo {
            get {
                return ResourceManager.GetString("Main_pro_bootblo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlocking bootloader....
        /// </summary>
        internal static string Main_pro_bootdes {
            get {
                return ResourceManager.GetString("Main_pro_bootdes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure the app like the picture and force close the app to apply the changes..
        /// </summary>
        internal static string Main_pro_precam {
            get {
                return ResourceManager.GetString("Main_pro_precam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://forum.xda-developers.com/mi-a1/how-to/tool-google-camera-root-magisk-enable-t3747585.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rebooting....
        /// </summary>
        internal static string reiniciar {
            get {
                return ResourceManager.GetString("reiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Booting twrp....
        /// </summary>
        internal static string twrp {
            get {
                return ResourceManager.GetString("twrp", resourceCulture);
            }
        }
    }
}
